{
  "code": 2,
  "subdomains": {
    "assert": {
      "code": 1,
      "errors": {
        "invalid_type": {
          "description": "Wrong argument type",
          "code": 1,
          "message": "Wrong type for argument \"%s\" (expected: %s)",
          "class": "BadRequestError"
        },
        "invalid_argument": {
          "description": "A request argument holds an invalid value",
          "code": 2,
          "message": "Invalid argument \"%s\". Expected: %s",
          "class": "BadRequestError"
        },
        "missing_argument": {
          "description": "A required argument is missing"
          "code": 3,
          "message": "Missing agument \"%s\".",
          "class": "BadRequestError"
        },
        "empty_argument": {
          "description": "The argument cannot be empty",
          "code": 4,
          "message": "The argument \"%s\" is empty.",
          "class": "BadRequestError"
        },
        "mutually_exclusive": {
          "description": "Mutually exclusive parameters have been provided",
          "code": 5,
          "message": "Arguments \"%s\" and \"%s\" are mutually exclusive",
          "class": "BadRequestError"
        },
        "too_many_arguments": {
          "description": "An argument contains too many keys or values",
          "code": 6,
          "message": "Argument \"%s\" contains too many values",
          "class": "BadRequestError"
        },
        "unexpected_argument": {
          "description": "An unexpected argument has been provided",
          "code": 7,
          "message": "Unexpected argument \"%s\" (accepted arguments: %s)",
          "class": "BadRequestError"
        },
        "body_required": {
          "description": "A request body is required",
          "code": 8,
          "message": "The request must specify a body.",
          "class": "BadRequestError"
        },
        "unexpected_type_assertion": {
          "description": "Unexpected type assertion",
          "code": 9,
          "message": "An unexepected type assertion \"%s\" has been invoked on attribute \"%s\".",
          "class": "InternalError"
        },
        "invalid_id": {
          "description": "_id values cannot start with an underscore",
          "code": 10,
          "message": "Invalid \"_id\" value: cannot start with an underscore",
          "class": "BadRequestError"
        }
      }
    },
    "process": {
      "code": 2,
      "errors": {
        "action_locked": {
          "description": "Cannot execute the requested action because it's already executing",
          "code": 1,
          "message": "Cannot execute action \"%s\": already executing.",
          "class": "PreconditionError"
        },
        "overloaded": {
          "description": "The request has been discarded because the server is overloaded",
          "code": 2,
          "message": "Request discarded: Kuzzle Server is temporarily overloaded.",
          "class": "ServiceUnavailableError"
        },
        "connection_dropped": {
          "description": "The request has been discarded because its linked client connection has dropped",
          "code": 3,
          "message": "Client connection dropped",
          "class": "BadRequestError"
        },
        "unknown_controller": {
          "description": "Unknown API controller",
          "code": 4,
          "message": "Unknown controller %s.",
          "class": "BadRequestError"
        },
        "unknown_action": {
          "description": "Unknown API controller action",
          "code": 5,
          "message": "No corresponding action %s in controller %s.",
          "class": "BadRequestError"
        }
      }
    }
  }
}
