{
  "code": 3,
  "subdomains": {
    "http": {
      "code": 1,
      "errors": {
        "request_too_large": {
          "description": "The size of the request exceeds the server configured limit",
          "code": 1,
          "message": "Maximum HTTP request size exceeded.",
          "class": "SizeLimitError"
        },
        "unexpected_error": {
          "description": "Caught an unexpected HTTP parsing error",
          "code": 2,"
          "message": "%s",
          "class": "BadRequestError"
        },
        "too_many_encodings": {
          "description": "The number of encodings exceeds the server configured limit",
          "code": 3,
          "message": "Too many encodings.",
          "class": "BadRequestError"
        },
        "unsupported_compression": {
          "description": "The request has been compressed using an unsupported compression algorithm",
          "code": 4,
          "message": "Unsupported compression algorithm \"%s\".",
          "class": "BadRequestError"
        },
        "compression_disabled": {
          "desscription": "The server has been configured to refuse compressed requests",
          "code": 5,
          "message": "Compression support is disabled.",
          "class": "BadRequestError"
        }
      }
    },
    "mqtt": {
      "code": 2,
      "errors": {
        "mqtt_request_error": {
          "code": 1,
          "message": "%s.",
          "class": "BadRequestError"
        }
      }
    },
    "websocket": {
      "code": 3,
      "errors": {
        "websocket_request_error": {
          "code": 1,
          "message": "%s.",
          "class": "BadRequestError"
        }
      }
    }
    "entrypoint": {
      "code": 5,
      "errors": {
        "unexpected_event": {
          "description": "Received an erroneous network event",
          "code": 1,
          "message": "Unexpected event received: %s.",
          "class": "InternalError"
        },
        "invalid_port": {
          "description": "Invalid network port",
          "code": 2,
          "message": "Invalid network port number: %s.",
          "class": "InternalError"
        }
      }
    },
    "http_router": {
      "code": 6,
      "errors": {
        "unrecognized_http_method": {
          "code": 1,
          "message": "Unrecognized HTTP method %s.",
          "class": "BadRequestError"
        },
        "api_url_not_found": {
          "code": 2,
          "message": "API URL not found: %s.",
          "class": "NotFoundError"
        },
        "invalid_request_content_type": {
          "code": 3,
          "message": "Invalid request content-type. Expected \"application/json\", got: \"%s\".",
          "class": "BadRequestError"
        },
        "invalid_request_charset": {
          "code": 4,
          "message": "Invalid request charset. Expected \"utf-8\", got: \"%s\".",
          "class": "BadRequestError"
        },
        "unable_to_attach_url": {
          "code": 5,
          "message": "Unable to attach URL %s: URL path already exists.",
          "class": "InternalError"
        },
        "part_already_exists": {
          "code": 6,
          "message": "part already exists.",
          "class": "InternalError"
        },
        "unable_to_convert_http_header_to_json": {
          "code": 7,
          "message": "Unable to convert HTTP x-kuzzle-volatile header to JSON.",
          "class": "BadRequestError"
        },
        "unable_to_convert_http_body_to_json": {
          "code": 8,
          "message": "Unable to convert HTTP body to JSON.",
          "class": "BadRequestError"
        },
        "request_error": {
          "code": 9,
          "message": "%s.",
          "class": "InternalError"
        }
      }
    }
  }
}
